version: '3'

services:
  postgres:
    image: postgres:12
    ports:
      - 10003:5432
    volumes:
      - ./var/postgresql-data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: db_dev
      POSTGRES_USER: db_dev
      POSTGRES_PASSWORD: db_dev
